### ISSUE TITLE
Can't get logged in user through request.user

### ISSUE THREAD

**Issue by naouflex** [ManaanAnsari/MetaMask-Login-Python#1]
This is a great introduction to login with Metamask and the article make it clear as water, thanks for such a contribution.

It seems that django Middleware can't get the currently logged in Web3User (through request.user)  making it hard to deal with objects or model ownership : it returns always an AnonymousUser.

**Comment by ManaanAnsari** [comment]
not really 
if you see the settings file 
we are using rest framework's Token authentication 

logged-in user will have to pass the authorization Header with the request 
request.user will contain the logged-in user object 

you can also use rest frameworks [isAuthenticated](https://www.django-rest-framework.org/api-guide/permissions/) permission for an API to only allow loggedin user 


ps : the best way would be to implement simple jwt but I wanted to keep this article simple 
https://github.com/jazzband/djangorestframework-simplejwt

and I am glad you liked the article Thanks :)

**Comment by naouflex** [comment]
I implemented it for my project and it works great for authentication or in combination with private routes. I am just having troubles using it as an authentication backend and add permissions to it so Web3Users can manage their objects.

I'll have a look at simple jwt thank you ! Do you have an example of a repo using it for this purpose by any chance ?

Edit: fixed by passing the user info into request header
